### ISSUE TITLE
Additional authenticators

### ISSUE THREAD

**Issue by markguinn** [notthatbad/silverstripe-rest-api#11]
I need to implement some additional authentication options for a project I'm working on. I'm going to add the ability to login with an oauth access_token from a social site (e.g. Facebook). The token will be obtained on the client and then verified on the server and if it's valid the user will be considered signed in without a password.

This could require some changes to the session controller, validator, and the authentication interface. Are those features you'd like to see submitted back to this module? Or would you prefer I keep the changes with my application's codebase, or possibly as a addon module to this one? Either is fine with me. It's probably about the same amount of work both ways.

**Comment by 1blankz7** [comment]
Currently we have oauth in our application code. This is not the best solution. I think a generic solution would be very helpful.

I would like to see an addon module to this one and not a direct integration of oauth into this module. If you would like, then I can submit a new module (eg. `silverstripe-rest-api-oauth`).

**Comment by markguinn** [comment]
Here is the WIP code I've got for that currently: https://gist.github.com/markguinn/203557ab0e5895b0f098 (For some reason PHP Storm prefixed all the filenames with "auth_" when I created the gist)

Feel free to use this or if it's helpful. I chose not to use any of the existing php social api libraries because most of them are quite complex and there possibly open up access points I don't necessarily want and because the simple task of using an existing access token to validate a user is pretty simple in every social API I'm aware of.

I think there are a few more tweaks to this that will need to be added (e.g. checking that the access_token is not from a different fb app id by sending a hash of the secret).

**Comment by 1blankz7** [comment]
In c3727fd I have added the ability to configure the validator. So you can use another authenticator as well. https://github.com/notthatbad/silverstripe-rest-api-oauth is the new module which you can use for your project.

**Comment by markguinn** [comment]
Thanks, Christian, this is great. I'll contribute PR's as our own project develops.

**Comment by 1blankz7** [comment]
That would be great. I will add Google+ as soon as I wipe off the application dependencies.
