### ISSUE TITLE
Delete route seems off

### ISSUE THREAD

**Issue by markguinn** [notthatbad/silverstripe-rest-api#7]
The way the SessionController is set up right now, you'd need to `DELETE /v/1/sessions/delete/me` which doesn't seem very intuitive. Shouldn't it just be `DELETE /v/1/sessions` or `DELETE /v/1/sessions/current` or something?

**Comment by 1blankz7** [comment]
In our tests we use something along this lines:

```
public function testDeleteSession() {
    $session = $this->createSession();
    $this->makeApiRequest('sessions/me', ['token' => $session['token'], 'method' => 'DELETE']);
}

private function createSession() {
    $data = [
        'email' => 'considine.colby@gmail.com',
        'password' => 'password'
    ];
    $dataString = json_encode($data);
    $result = $this->makeApiRequest('sessions', ['body' => $dataString, 'method' => 'POST']);
    return $result['session'];
}
```

The BaseRestController overwrites the default Silverstripe mechanism, so the actions (e.g. `DELETE`) are called according to the current http method.

**Comment by markguinn** [comment]
That's interesting. What version of SS are you using? I'm doing almost the same in my test (except using SimpleAuth instead of tokens) and the 'sessions/me' url didn't work. I had to use 'sessions/delete/me'.

```
$mySession = new Session(['loggedInAs' => $myUser->ID]);
$this->makeApiRequest('sessions/delete/me', ['session' => $mySession, 'method' => 'DELETE']);
```

I'm using SS 3.2.1. It's not a big deal as I'm already subclassing your SessionController to add a get method so I can override delete as well for my own case. But it may be worth investigating at any rate.

**Comment by 1blankz7** [comment]
I will try to reproduce this on friday. Maybe I will find the problem.

**Comment by markguinn** [comment]
It looks to me like the problem is how I had my routes set up. This works:

```
    'api/v1/session/$ID/$OtherID': SessionController
```

These don't:

```
    'api/v1/session//$ID/$OtherID': SessionController
    'api/v1/session': SessionController
```

Thanks!

**Comment by 1blankz7** [comment]
That is a good point. We should a some advices for route definitions. For example you must add nested routes before the main route.

```
'v/1/users/$ID!/friends/$FriendID': 'FriendshipController'
'v/1/users/$ID': 'UserController'
```
